const unified = require('unified')
const stream = require('unified-stream')
const markdown = require('remark-parse')
const remark2rehype = require('remark-rehype')
const format = require('rehype-format')
const html = require('rehype-stringify')
const raw = require('rehype-raw')
const externalLinks = require('remark-external-links')

const processor = unified()
  .use(markdown)
  .use(externalLinks, { rel: ['noopener', 'noreferrer'] })
  .use(remark2rehype, { allowDangerousHTML: true })
  .use(raw)
  .use(format)
  .use(html)

process.stdin.pipe(stream(processor)).pipe(process.stdout)
