on:
  push:
    branches:
      - master
name: Publish
jobs:
  npm-publish:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.0.0
      - uses: pascalgn/npm-publish-action@master
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^publish: (\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}